# Usar una versión específica de MySQL (por ejemplo, 8.0)
FROM mysql:8.0

# Definir variables de entorno para la base de datos
ENV MYSQL_ROOT_PASSWORD="hola123"
ENV MYSQL_DATABASE="productos_db"

# Exponer el puerto 3306 para conexiones MySQL
EXPOSE 3306

# Comando para iniciar MySQL
CMD ["mysqld"]


