# Usar la última versión oficial de MySQL
FROM mysql:latest  

# Definir variables de entorno para la base de datos
ENV MYSQL_ROOT_PASSWORD=""
ENV MYSQL_DATABASE="productos_db"
ENV MYSQL_USER="root"
ENV MYSQL_PASSWORD=""

# Exponer el puerto 3306 para conexiones MySQL
EXPOSE 3306  

# Comando para iniciar MySQL
CMD ["mysqld"]  
